from collections import defaultdict


class OperationRules:

    def __init__(self):

        self.types = defaultdict(lambda: defaultdict(lambda: defaultdict(lambda: 'unknown')))
        self.unary_types = defaultdict(lambda: defaultdict(lambda: 'unknown'))

        self.types['+']['int']['int'] = 'int'
        self.types['+']['float']['float'] = 'float'
        self.types['+']['int']['float'] = 'float'
        self.types['+']['float']['int'] = 'float'
        self.types['+']['string']['string'] = 'string'

        self.types['-']['int']['int'] = 'int'
        self.types['-']['float']['float'] = 'float'
        self.types['-']['int']['float'] = 'float'
        self.types['-']['float']['int'] = 'float'

        self.types['*']['int']['int'] = 'int'
        self.types['*']['float']['float'] = 'float'
        self.types['*']['int']['float'] = 'float'
        self.types['*']['float']['int'] = 'float'
        self.types['*']['vector']['int'] = 'vector'
        self.types['*']['int']['vector'] = 'vector'
        self.types['*']['vector']['float'] = 'vector'
        self.types['*']['float']['vector'] = 'vector'
        self.types['*']['matrix']['matrix'] = 'matrix'
        self.types['*']['matrix']['vector'] = 'matrix'

        self.types['/']['int']['int'] = 'float'
        self.types['/']['float']['float'] = 'float'
        self.types['/']['int']['float'] = 'float'
        self.types['/']['float']['int'] = 'float'
        self.types['/']['vector']['int'] = 'vector'
        self.types['/']['vector']['float'] = 'vector'

        self.types['+=']['int']['int'] = 'int'
        self.types['+=']['float']['float'] = 'float'
        self.types['+=']['int']['float'] = 'float'
        self.types['+=']['float']['int'] = 'float'

        self.types['-=']['int']['int'] = 'int'
        self.types['-=']['float']['float'] = 'float'
        self.types['-=']['int']['float'] = 'float'
        self.types['-=']['float']['int'] = 'float'

        self.types['*=']['int']['int'] = 'int'
        self.types['*=']['float']['float'] = 'float'
        self.types['*=']['int']['float'] = 'float'
        self.types['*=']['float']['int'] = 'float'
        self.types['*=']['vector']['int'] = 'vector'
        self.types['*=']['vector']['float'] = 'vector'
        self.types['*=']['matrix']['matrix'] = 'matrix'
        self.types['*=']['matrix']['vector'] = 'matrix'

        self.types['/=']['int']['int'] = 'int'
        self.types['/=']['float']['float'] = 'float'
        self.types['/=']['int']['float'] = 'float'
        self.types['/=']['float']['int'] = 'float'
        self.types['/=']['vector']['int'] = 'vector'
        self.types['/=']['vector']['float'] = 'vector'

        self.types['.+']['vector']['vector'] = 'vector'
        self.types['.+']['matrix']['matrix'] = 'matrix'
        self.types['.+']['matrix']['int'] = 'matrix'
        self.types['.+']['matrix']['float'] = 'matrix'
        self.types['.+']['vector']['int'] = 'vector'
        self.types['.+']['vector']['float'] = 'vector'
        self.types['.+']['int']['matrix'] = 'matrix'
        self.types['.+']['float']['matrix'] = 'matrix'
        self.types['.+']['int']['vector'] = 'vector'
        self.types['.+']['float']['vector'] = 'vector'

        self.types['.-']['vector']['vector'] = 'vector'
        self.types['.-']['matrix']['matrix'] = 'matrix'
        self.types['.-']['matrix']['int'] = 'matrix'
        self.types['.-']['matrix']['float'] = 'matrix'
        self.types['.-']['vector']['int'] = 'vector'
        self.types['.-']['vector']['float'] = 'vector'
        self.types['.-']['int']['matrix'] = 'matrix'
        self.types['.-']['float']['matrix'] = 'matrix'
        self.types['.-']['int']['vector'] = 'vector'
        self.types['.-']['float']['vector'] = 'vector'

        self.types['.*']['vector']['vector'] = 'vector'
        self.types['.*']['matrix']['matrix'] = 'matrix'
        self.types['.*']['matrix']['int'] = 'matrix'
        self.types['.*']['matrix']['float'] = 'matrix'
        self.types['.*']['vector']['int'] = 'vector'
        self.types['.*']['vector']['float'] = 'vector'
        self.types['.*']['int']['matrix'] = 'matrix'
        self.types['.*']['float']['matrix'] = 'matrix'
        self.types['.*']['int']['vector'] = 'vector'
        self.types['.*']['float']['vector'] = 'vector'

        self.types['./']['vector']['vector'] = 'vector'
        self.types['./']['matrix']['matrix'] = 'matrix'
        self.types['./']['matrix']['int'] = 'matrix'
        self.types['./']['matrix']['float'] = 'matrix'
        self.types['./']['vector']['int'] = 'vector'
        self.types['./']['vector']['float'] = 'vector'
        self.types['./']['int']['matrix'] = 'matrix'
        self.types['./']['float']['matrix'] = 'matrix'
        self.types['./']['int']['vector'] = 'vector'
        self.types['./']['float']['vector'] = 'vector'

        self.types['==']['int']['int'] = 'boolean'
        self.types['==']['float']['float'] = 'boolean'
        self.types['==']['int']['float'] = 'boolean'
        self.types['==']['float']['int'] = 'boolean'
        self.types['==']['string']['string'] = 'boolean'
        self.types['==']['vector']['vector'] = 'boolean'
        self.types['==']['matrix']['matrix'] = 'boolean'

        self.types['!=']['int']['int'] = 'boolean'
        self.types['!=']['float']['float'] = 'boolean'
        self.types['!=']['int']['float'] = 'boolean'
        self.types['!=']['float']['int'] = 'boolean'
        self.types['!=']['string']['string'] = 'boolean'
        self.types['!=']['vector']['vector'] = 'boolean'
        self.types['!=']['matrix']['matrix'] = 'boolean'

        self.types['>']['int']['int'] = 'boolean'
        self.types['>']['float']['float'] = 'boolean'
        self.types['>']['int']['float'] = 'boolean'
        self.types['>']['float']['int'] = 'boolean'
        self.types['>']['string']['string'] = 'boolean'
        self.types['>']['vector']['vector'] = 'boolean'
        self.types['>']['matrix']['matrix'] = 'boolean'

        self.types['<']['int']['int'] = 'boolean'
        self.types['<']['float']['float'] = 'boolean'
        self.types['<']['int']['float'] = 'boolean'
        self.types['<']['float']['int'] = 'boolean'
        self.types['<']['string']['string'] = 'boolean'
        self.types['<']['vector']['vector'] = 'boolean'
        self.types['<']['matrix']['matrix'] = 'boolean'

        self.types['>=']['int']['int'] = 'boolean'
        self.types['>=']['float']['float'] = 'boolean'
        self.types['>=']['int']['float'] = 'boolean'
        self.types['>=']['float']['int'] = 'boolean'
        self.types['>=']['string']['string'] = 'boolean'
        self.types['>=']['vector']['vector'] = 'boolean'
        self.types['>=']['matrix']['matrix'] = 'boolean'

        self.types['<=']['int']['int'] = 'boolean'
        self.types['<=']['float']['float'] = 'boolean'
        self.types['<=']['int']['float'] = 'boolean'
        self.types['<=']['float']['int'] = 'boolean'
        self.types['<=']['string']['string'] = 'boolean'
        self.types['<=']['vector']['vector'] = 'boolean'
        self.types['<=']['matrix']['matrix'] = 'boolean'

        self.unary_types['NEGATE']['int'] = 'int'
        self.unary_types['NEGATE']['float'] = 'float'
        self.unary_types['NEGATE']['vector'] = 'vector'
        self.unary_types['NEGATE']['matrix'] = 'matrix'

        self.unary_types['TRANSPOSE']['vector'] = 'matrix'
        self.unary_types['TRANSPOSE']['matrix'] = 'matrix'
